import { WorkOrder, AlertNotice, WorkHistoryLog, CampusZone, SystemLogItem, LaborerProfile } from '../types';

export const initialLaborerProfile: LaborerProfile = {
  name: 'Kasun Perera',
  employeeId: 'EMP-T8402',
  title: 'Senior HVAC & Electrical Technician',
  division: 'Central Maintenance Division',
  institution: 'Institute of Technology, University of Moratuwa',
  isOnDuty: true,
  shift: 'Shift 1 (08:00 AM – 05:00 PM)',
  workshopBase: 'Workshop Bay 3',
  totalJobs: 142,
  satisfactionRating: 4.9,
  attendanceRate: '100%',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCEWRH06Wr_jVDeWhraMa89yVAS5PuqahaXycJqIG_rseR7pac7Ghv0dCrPxdB2aNQtlyCn1B0XqKwmp--g1zTs_oSXKbL77R9oKWXFUeT8WJHFfjezW-SFWAptCEwqlbveOQKJtXDNByX0TU0qsP_V5WmCVp4zwj8cHNE-zQOOuh7PyoQfJT7b8YoJpYMeppGIPAl8DUOYij_Rgo-WJgt8v-iiCmiJQ7P501yuJwwWeY662nY-4x5ObA',
  pushNotificationsEnabled: true,
  emergencyRingtoneOverride: true,
  language: 'en',
  assignedZones: ['zone-1', 'zone-2', 'zone-3'],
};

export const initialWorkOrders: WorkOrder[] = [
  {
    id: 'REQ-8291',
    jobCode: 'JOB-1024',
    title: 'AC Leakage & Cooling Failure',
    category: 'AC REPAIR',
    description: 'AC unit is leaking water onto student study desks and stopped cooling properly since early morning. Frost formation observed on main line. Requires urgent coil inspection and filter change before mid-day lecture.',
    department: 'General Administration',
    location: 'Library, Floor 2, Room U2018',
    subLocation: 'Above Study Carrel 4 • South Wing',
    priority: 'HIGH',
    status: 'In Progress',
    assignedTime: '08:30 AM',
    dueTime: '11:30 AM (Shift 1)',
    requesterName: 'Mrs. Oshini Hewage',
    requesterDept: 'General Administration',
    requesterExt: '412',
    reportedPhotoUrl: 'https://lh3.googleusercontent.com/aida/AEtjO1XFMlkzaMs85K5FOQgq0UE2g96V7M8LwIG0hb8oUQE0rIxbv6lBeqmxRRRHBTR4Ienm1odSbWMCBAUF5w9IxALhkc61nQyTaLZz8xIhXLYsRXdbE_LypMkMAWuFjyQq4ofSHwobGwKI6zw5ninJfTFC1xQr05Zt6FzfPKVAd3GsvWYTIbeqJVwOn9pIbuo9VYXDLa9UNjmqHak8z3Oaklu7GrPsTxkwy_Czysr57oTTu3q1UOcSdnwFm-U',
    reportedPhotoTimestamp: '08:15 AM',
    partsUsed: ['Filter Mesh (OEM-F40)', 'Drain Pipe Flush Seal'],
    technicianRemarks: 'Inspected compressor coil. Frost cleared. Drain line flushed.',
  },
  {
    id: 'REQ-8254',
    jobCode: 'JOB-1025',
    title: 'Electrical Socket Replacement',
    category: 'ELECTRICAL',
    description: 'Burned bench terminal near power distribution rack 4. Replace faceplate & inspect wiring.',
    department: 'Faculty of Electrical Engineering',
    location: 'Science Building, Lab Annex U1134',
    subLocation: 'Bench Terminal #4 • Distribution Rack B',
    priority: 'MEDIUM',
    status: 'Pending Start',
    assignedTime: '10:30 AM',
    dueTime: '01:30 PM Today',
    requesterName: 'Dr. K. Liyanage',
    requesterDept: 'Electrical Engineering',
    requesterExt: '315',
  },
  {
    id: 'REQ-8279',
    jobCode: 'JOB-1022',
    title: 'Water Leakage Inspection',
    category: 'PLUMBING',
    description: 'Active valve drip causing water pooling beneath chemical wash sink basin.',
    department: 'Department of Chemistry',
    location: 'Chemistry Lab, Floor 1, Sink Line 4',
    subLocation: 'Chemical Wash Basin 4',
    priority: 'HIGH',
    status: 'Completed',
    assignedTime: '01:15 PM',
    dueTime: '03:00 PM',
    requesterName: 'Prof. S. Wickramasinghe',
    requesterDept: 'Chemical & Process Eng.',
    requesterExt: '508',
    technicianRemarks: 'Standard Diaphragm Kit Replaced.',
  },
  {
    id: 'REQ-8285',
    jobCode: 'JOB-1020',
    title: 'Fluorescent Light Fixture Repair',
    category: 'ELECTRICAL',
    description: 'Flickering high-bay ballast fixture near stage left. Ballast coil humming excessively.',
    department: 'University Administration',
    location: 'Main Auditorium, Stage Area (Zone B)',
    subLocation: 'High-Bay Ceiling Grid #12',
    priority: 'MEDIUM',
    status: 'Signed Off',
    assignedTime: '02:00 PM',
    dueTime: '04:30 PM',
    requesterName: 'Mr. T. Bandara',
    requesterDept: 'Facilities Management',
    requesterExt: '402',
    verifierName: 'Dr. Wickramasinghe',
    verifierRole: 'Head of Department',
  },
];

export const initialAlertNotices: AlertNotice[] = [
  {
    id: 'ALT-901',
    title: 'Water Main Line Burst - Chemical Lab 102',
    description: 'Immediate emergency isolation required before electrical panels short. Lab technician awaiting at location.',
    category: 'hazard',
    severity: 'CRITICAL',
    timestamp: '5 mins ago',
    location: 'Department of Chemical & Process Eng. • Floor 1',
    isRead: false,
    actionType: 'navigate',
  },
  {
    id: 'ALT-902',
    title: 'High Voltage Warning - Substation B',
    description: 'Unscheduled breaker trip reported by campus security. Do not enter without certified safety gear and arc-flash face shield.',
    category: 'hazard',
    severity: 'HIGH',
    timestamp: '25 mins ago',
    location: 'Substation B • Sector 4',
    isRead: false,
    actionType: 'view_advisory',
  },
  {
    id: 'ALT-903',
    title: 'AC Compressor Overheating - Library',
    description: 'Floor 2 Room U2018. Dispatched by Maintenance Officer Bandara. Unit cycling off under thermal load.',
    category: 'dispatch',
    severity: 'INFO',
    timestamp: '1 hour ago',
    reqNumber: '#REQ-8292',
    isRead: false,
    actionType: 'open_ticket',
  },
  {
    id: 'ALT-904',
    title: 'Parts Approved: 2x Filter Mesh (OEM-F40)',
    description: 'Central Maintenance Store confirmed parts are reserved and ready for pickup at HazMat Bay 1 counter.',
    category: 'dispatch',
    severity: 'INFO',
    timestamp: '2 hours ago',
    pickupToken: '#PK-4091',
    isRead: false,
    actionType: 'pickup_token',
  },
  {
    id: 'ALT-905',
    title: 'Serva Sync Scheduled Downtime',
    description: 'Mobile server update tonight at 23:00 - 23:30. Offline caching will automatically buffer your field logs.',
    category: 'system',
    severity: 'INFO',
    timestamp: 'Yesterday',
    isRead: false,
  },
];

export const initialWorkHistory: WorkHistoryLog[] = [
  {
    id: 'HIST-801',
    reqCode: '#REQ-8285',
    title: 'Fluorescent Ballast Unit Replacement',
    division: 'Electrical Division',
    resolvedAt: 'Resolved at 04:15 PM',
    durationSpent: '1h 30m spent',
    location: 'Main Auditorium, Stage Area (Zone B)',
    status: 'Completed',
    verifierName: 'Dr. Wickramasinghe',
    verifierTitle: 'Head of Department • Digital Signature Authenticated',
    photosCount: 2,
    photoThumbnails: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAm84UGWK9BoQ1beXiCNHf4gcXpMfp6DWzoIVKvJQKIQeNllURyL_usxq9rDcrxdaqILWGtuwphTz69n3xCo8ek7nAKYlfQbqOVUqJC7Elcrcewx0GA6dmHj75fbMS0X2dPQvcK6kboRDq6X0lQYsZU_dKjg7OEHWz4m6cggssJ5FGtN9bEAC0fSvVd-fV7QOoEwF26LCzf0m19Q5SWey0p5j1dg7o2oZJam_THQ7oPvst0lKRQEgVA',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDTuWZvUv6g8lB2LMhRnk_EcyDMlMZooBC-faL3B_wTilcd-jXEMGdDkZ6RnBWW0YD-i3GjZkD_uTCl-JtGwEn4xOaRTEFz2DhTRl7BlltpD2GAjPgkia57L_Zd8RZ8-Y6NeYDsbkBGWwY1TiUJTkpROMVPYakrr2oJAvgNMWHciYtDq5dRj10mB_r3okwf519RKDqZPL0ae7fbhDudWwZGU11_NVuK5nQofm0Af5-moPqJIx4JgYHJqw'
    ],
  },
  {
    id: 'HIST-802',
    reqCode: '#REQ-8279',
    title: 'Restroom Flush Valve Repair',
    division: 'Plumbing Division',
    resolvedAt: 'Resolved at 11:45 AM',
    durationSpent: '45m spent',
    location: 'Faculty of Engineering, Ground Floor West',
    status: 'Completed',
    remarksSnippet: 'Standard Diaphragm Kit Replaced',
  },
  {
    id: 'HIST-803',
    reqCode: '#REQ-8260',
    title: 'Server Room Air Conditioner Gas Refill',
    division: 'HVAC Systems',
    resolvedAt: 'Resolved at 02:30 PM',
    durationSpent: '2h 15m spent',
    location: 'IT Center Room 102 (Server Matrix)',
    status: 'Signed Off',
    remarksSnippet: 'R-410A Refill 2.5kg',
    photosCount: 1,
    photoThumbnails: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBVLVsU8RQgn97JUTj4h6RmlrsCcRWlMT7Hk9VFswn_vFCXmIoFUOIPb6pyLUiXakoIcibSaW2Sfs0oR8BgiGi2HvWHV4dUkHkABuV6WY1wbELQKu5TCk7a8SRSvuuQ-hf3qEhcFid9KXhuKVw0MFeIRKrj4h2Iv8v5aF-jp9jaoN3oWzCl9q3L3Vo72htlCNZtqGJC7puuafszKHzVcZ2IgkDa0BPEsl0kkWWEOogj5IXtrSeYtA4OTQ'
    ]
  },
  {
    id: 'HIST-804',
    reqCode: '#REQ-8254',
    title: 'Overhead Projector Power Socket Fixture',
    division: 'Electrical Division',
    resolvedAt: 'Resolved at 10:10 AM',
    durationSpent: '35m spent',
    location: 'Civil Eng Building, Lecture Hall A',
    status: 'Completed',
    remarksSnippet: 'Replaced burnt terminal block',
  }
];

export const initialCampusZones: CampusZone[] = [
  {
    id: 'zone-1',
    name: 'Sector 1 - Engineering & Admin Complex',
    buildingsCount: 6,
    assignedLaborers: 8,
    activeTickets: 3,
    isCachedOffline: true,
    status: 'Active Assignment',
  },
  {
    id: 'zone-2',
    name: 'Sector 2 - Central Library & Auditorium',
    buildingsCount: 4,
    assignedLaborers: 5,
    activeTickets: 2,
    isCachedOffline: true,
    status: 'Active Assignment',
  },
  {
    id: 'zone-3',
    name: 'Sector 3 - Science & Chemistry Labs',
    buildingsCount: 5,
    assignedLaborers: 6,
    activeTickets: 4,
    isCachedOffline: true,
    status: 'Active Assignment',
  },
  {
    id: 'zone-4',
    name: 'Sector 4 - Substation & Workshops',
    buildingsCount: 3,
    assignedLaborers: 4,
    activeTickets: 1,
    isCachedOffline: false,
    status: 'Secondary Zone',
  }
];

export const initialSystemLogs: SystemLogItem[] = [
  {
    id: 'LOG-101',
    timestamp: '2026-08-22 14:32:10',
    severity: 'INFO',
    action: 'User Login Successful',
    userRole: 'Maintenance Officer',
    module: 'Auth',
    ipAddress: '192.248.64.12',
    details: 'Session #8942 Active • SLST Time Stamp',
  },
  {
    id: 'LOG-102',
    timestamp: '2026-08-22 14:15:05',
    severity: 'ERROR',
    action: 'Database Connection Timeout',
    userRole: 'System Gateway',
    module: 'Database',
    ipAddress: '192.248.64.02',
    details: 'Failed replica sync on node DB-02 • Retry scheduled',
  },
  {
    id: 'LOG-103',
    timestamp: '2026-08-22 13:45:22',
    severity: 'WARNING',
    action: 'Unauthorized Access Attempt',
    userRole: 'Unknown Device',
    module: 'Security',
    ipAddress: '192.248.64.99',
    details: '3 consecutive invalid password attempts blocked',
  },
  {
    id: 'LOG-104',
    timestamp: '2026-08-22 12:10:00',
    severity: 'INFO',
    action: 'Updated System Settings',
    userRole: 'Maintenance Officer',
    module: 'Settings',
    ipAddress: '192.248.64.12',
    details: 'Modified email notification thresholds for Tier 1 calls',
  },
  {
    id: 'LOG-105',
    timestamp: '2026-08-22 11:05:00',
    severity: 'INFO',
    action: 'Job #JOB-1024 Dispatched',
    userRole: 'Maintenance Officer',
    module: 'Jobs',
    ipAddress: '192.248.64.12',
    details: 'Assigned to Kasun Perera (HVAC) • High Priority SLA',
  },
];
